version: 2

sources:
  - name: airbyte_google_ads
    database: data-analysis-415012
    schema: airbyte_google_ads
    tables:
      - name: airbyte_campaign
        description: "Raw Google Ads campaign data from Airbyte"

  - name: non_pii
    database: data-analysis-415012
    schema: non_pii
    tables:
      - name: campaign_man
        description: "Non-PII campaign management data"
      - name: campaign_ad_accounts_ad_campaigns_map
        description: "Campaigns Map"